services:
  api:
    container_name: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    develop:
      watch:
        - path: ./backend
          action: rebuild
    ports:
      - "8080:8080"
