name: frontend/bun-vite-react-app

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/bun-vite-react-app/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/bun-vite-react-app/**'

jobs:
  lint-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: cd frontend/bun-vite-react-app && bun install

      - name: Run lint
        run: cd frontend/bun-vite-react-app && bun lint

      - name: Run format
        run: cd frontend/bun-vite-react-app && bun fmt:check
